export const mockTransactions = [
    {
        id: 1,
        title: "Monthly Salary",
        amount: 55000,
        type: "income",
        category: "Income",
        date: "2025-10-01",
    },
    {
        id: 2,
        title: "Dinner at Meghana Foods",
        amount: 950,
        type: "expense",
        category: "Food",
        date: "2025-10-05",
    },
    {
        id: 3,
        title: "Electricity Bill",
        amount: 1800,
        type: "expense",
        category: "Bills",
        date: "2025-10-08",
    },
    {
        id: 4,
        title: "Ola Cab to Airport",
        amount: 650,
        type: "expense",
        category: "Transport",
        date: "2025-10-12",
    },
    {
        id: 5,
        title: "Amazon Order - Books",
        amount: 1200,
        type: "expense",
        category: "Shopping",
        date: "2025-10-15",
    },
    {
        id: 6,
        title: "Swiggy Order",
        amount: 420,
        type: "expense",
        category: "Food",
        date: "2025-10-18",
    },
    {
        id: 7,
        title: "Netflix Subscription",
        amount: 649,
        type: "expense",
        category: "Bills",
        date: "2025-10-20",
    },
    {
        id: 8,
        title: "Freelance Project",
        amount: 12000,
        type: "income",
        category: "Income",
        date: "2025-10-22",
    },
    {
        id: 9,
        title: "Zomato Order",
        amount: 380,
        type: "expense",
        category: "Food",
        date: "2025-10-25",
    },
    {
        id: 10,
        title: "Metro Card Recharge",
        amount: 500,
        type: "expense",
        category: "Transport",
        date: "2025-10-28",
    },

    // November 2025
    {
        id: 11,
        title: "Monthly Salary",
        amount: 55000,
        type: "income",
        category: "Income",
        date: "2025-11-01",
    },
    {
        id: 12,
        title: "Grocery Shopping",
        amount: 2400,
        type: "expense",
        category: "Shopping",
        date: "2025-11-03",
    },
    {
        id: 13,
        title: "Water Bill",
        amount: 450,
        type: "expense",
        category: "Bills",
        date: "2025-11-06",
    },
    {
        id: 14,
        title: "Breakfast at Cafe",
        amount: 320,
        type: "expense",
        category: "Food",
        date: "2025-11-09",
    },
    {
        id: 15,
        title: "Rapido Bike",
        amount: 180,
        type: "expense",
        category: "Transport",
        date: "2025-11-12",
    },
    {
        id: 16,
        title: "Dinner with Friends",
        amount: 1800,
        type: "expense",
        category: "Food",
        date: "2025-11-15",
    },
    {
        id: 17,
        title: "Spotify Premium",
        amount: 119,
        type: "expense",
        category: "Bills",
        date: "2025-11-18",
    },
    {
        id: 18,
        title: "Side Project Income",
        amount: 8000,
        type: "income",
        category: "Income",
        date: "2025-11-20",
    },
    {
        id: 19,
        title: "Clothes Shopping",
        amount: 3200,
        type: "expense",
        category: "Shopping",
        date: "2025-11-23",
    },
    {
        id: 20,
        title: "Swiggy Order",
        amount: 450,
        type: "expense",
        category: "Food",
        date: "2025-11-26",
    },

    {
        id: 21,
        title: "Monthly Salary",
        amount: 55000,
        type: "income",
        category: "Income",
        date: "2025-12-01",
    },
    {
        id: 22,
        title: "Christmas Shopping",
        amount: 5500,
        type: "expense",
        category: "Shopping",
        date: "2025-12-05",
    },
    {
        id: 23,
        title: "Electricity Bill",
        amount: 2100,
        type: "expense",
        category: "Bills",
        date: "2025-12-08",
    },
    {
        id: 24,
        title: "Restaurant Dinner",
        amount: 2400,
        type: "expense",
        category: "Food",
        date: "2025-12-12",
    },
    {
        id: 25,
        title: "Flight Ticket",
        amount: 4500,
        type: "expense",
        category: "Transport",
        date: "2025-12-15",
    },
    {
        id: 26,
        title: "Year End Bonus",
        amount: 20000,
        type: "income",
        category: "Income",
        date: "2025-12-20",
    },
    {
        id: 27,
        title: "New Year Party",
        amount: 3200,
        type: "expense",
        category: "Food",
        date: "2025-12-28",
    },
    {
        id: 28,
        title: "Amazon Shopping",
        amount: 2800,
        type: "expense",
        category: "Shopping",
        date: "2025-12-30",
    },

    {
        id: 29,
        title: "Monthly Salary",
        amount: 55000,
        type: "income",
        category: "Income",
        date: "2026-01-01",
    },
    {
        id: 30,
        title: "Gym Membership",
        amount: 2000,
        type: "expense",
        category: "Bills",
        date: "2026-01-04",
    },
    {
        id: 31,
        title: "Lunch at Office",
        amount: 280,
        type: "expense",
        category: "Food",
        date: "2026-01-07",
    },
    {
        id: 32,
        title: "Ola Cab",
        amount: 220,
        type: "expense",
        category: "Transport",
        date: "2026-01-10",
    },
    {
        id: 33,
        title: "Freelance Work",
        amount: 15000,
        type: "income",
        category: "Income",
        date: "2026-01-14",
    },
    {
        id: 34,
        title: "Flipkart Order",
        amount: 1800,
        type: "expense",
        category: "Shopping",
        date: "2026-01-17",
    },
    {
        id: 35,
        title: "Dinner at Hotel",
        amount: 1600,
        type: "expense",
        category: "Food",
        date: "2026-01-20",
    },
    {
        id: 36,
        title: "Phone Bill",
        amount: 599,
        type: "expense",
        category: "Bills",
        date: "2026-01-23",
    },
    {
        id: 37,
        title: "Zomato Order",
        amount: 350,
        type: "expense",
        category: "Food",
        date: "2026-01-26",
    },

    {
        id: 38,
        title: "Monthly Salary",
        amount: 55000,
        type: "income",
        category: "Income",
        date: "2026-02-01",
    },
    {
        id: 39,
        title: "Valentine Dinner",
        amount: 3500,
        type: "expense",
        category: "Food",
        date: "2026-02-14",
    },
    {
        id: 40,
        title: "Electricity Bill",
        amount: 1600,
        type: "expense",
        category: "Bills",
        date: "2026-02-06",
    },
    {
        id: 41,
        title: "Metro Pass",
        amount: 500,
        type: "expense",
        category: "Transport",
        date: "2026-02-09",
    },
    {
        id: 42,
        title: "Myntra Shopping",
        amount: 2200,
        type: "expense",
        category: "Shopping",
        date: "2026-02-12",
    },
    {
        id: 43,
        title: "Freelance Project",
        amount: 10000,
        type: "income",
        category: "Income",
        date: "2026-02-18",
    },
    {
        id: 44,
        title: "Swiggy Order",
        amount: 480,
        type: "expense",
        category: "Food",
        date: "2026-02-20",
    },
    {
        id: 45,
        title: "Internet Bill",
        amount: 899,
        type: "expense",
        category: "Bills",
        date: "2026-02-24",
    },

    // March 2026
    {
        id: 46,
        title: "Monthly Salary",
        amount: 55000,
        type: "income",
        category: "Income",
        date: "2026-03-01",
    },
    {
        id: 47,
        title: "Dinner at Meghana Foods",
        amount: 850,
        type: "expense",
        category: "Food",
        date: "2026-03-05",
    },
    {
        id: 48,
        title: "Ola Cab to Office",
        amount: 220,
        type: "expense",
        category: "Transport",
        date: "2026-03-08",
    },
    {
        id: 49,
        title: "Netflix Subscription",
        amount: 649,
        type: "expense",
        category: "Bills",
        date: "2026-03-10",
    },
    {
        id: 50,
        title: "Amazon Order - Shoes",
        amount: 1299,
        type: "expense",
        category: "Shopping",
        date: "2026-03-14",
    },
    {
        id: 51,
        title: "Lunch at Cafe",
        amount: 380,
        type: "expense",
        category: "Food",
        date: "2026-03-17",
    },
    {
        id: 52,
        title: "Freelance Work",
        amount: 18000,
        type: "income",
        category: "Income",
        date: "2026-03-20",
    },
    {
        id: 53,
        title: "Electricity Bill",
        amount: 1900,
        type: "expense",
        category: "Bills",
        date: "2026-03-22",
    },
    {
        id: 54,
        title: "Rapido Bike",
        amount: 150,
        type: "expense",
        category: "Transport",
        date: "2026-03-25",
    },
    {
        id: 55,
        title: "Zomato Order",
        amount: 420,
        type: "expense",
        category: "Food",
        date: "2026-03-28",
    },
];
